(local nvim (require :aniseed.nvim))

(set vim.bo.suffixesadd ".fnl")
(set vim.g.paredit_leader "<leader>")
(set vim.bo.define "(\\(fn\\|macro\\|lambda\\|λ\\)\\s\\zs\\w")
(set vim.bo.include "(\\(require\\-macros\\|import\\-macros\\|require\\)")
(set vim.bo.includeexpr "substitute(v:fname,'\\.','/','g')")
(set vim.o.lispwords (.. vim.o.lispwords ",collect,icollect,with-open"))
(nvim.ex.packadd :conjure)
((. (require :conjure.mapping) :on-filetype))
